from pytpp.attributes._helper import PropertyMeta
from pytpp.attributes.agent_discovery_base import AgentDiscoveryBaseAttributes


class AgentCertificateDiscoveryAttributes(AgentDiscoveryBaseAttributes, metaclass=PropertyMeta):
	pass