from pytpp.attributes._helper import PropertyMeta
from pytpp.attributes.flow_action_config_read_approvers import FlowActionConfigReadApproversAttributes


class FlowActionTeamOwnerApprovalAttributes(FlowActionConfigReadApproversAttributes, metaclass=PropertyMeta):
	pass