from pytpp.attributes._helper import PropertyMeta
from pytpp.attributes.flow_action_base import FlowActionBaseAttributes


class SSHCertificateStartProcessingActionAttributes(FlowActionBaseAttributes, metaclass=PropertyMeta):
	pass