class ConfigClass:
    device = 'Device'
    policy = 'Policy'
    msca = 'Microsoft CA'
    self_signed = 'Self Signed CA'


class FolderAttributes:
    certificate_origin = 'Certificate Origin'
    contact = 'Contact'
    created_by = 'Created By'
    description = 'Description'
    disabled = 'Disabled'
    escalation_contact = 'Escalation Contact'
    guid = 'GUID'
    log_view_server = 'Log View Server'
    managed_by = 'Managed By'
    master_preferences = 'Master Preferences'
    metadata = 'Metadata'
    reference = 'Reference'
    scep_ca_ident = 'Scep CA Ident'
    scep_certificate_authority = 'Scep Certificate Authority'
    scep_challenge_password = 'Scep Challenge Password'
    scep_encryption_ra_certificate = 'Scep Encryption RA Certificate'
    scep_intune_application_id = 'Scep Intune Application Id'
    scep_intune_application_secret = 'Scep Intune Application Secret'
    scep_intune_tenant_name = 'Scep Intune Tenant Name'
    scep_ra_certificate = 'Scep RA Certificate'
    scep_selection_rule = 'Scep Selection Rule'
    scep_signing_ra_certificate = 'Scep Signing RA Certificate'
    workflow = 'Workflow'
    workflow_block = 'Workflow Block'


class _CredentialAttributes:
    contact = 'Contact'
    created_by = 'Created By'
    description = 'Description'
    disabled = 'Disabled'
    escalation_contact = 'Escalation Contact'
    escalation_notice_interval = 'Escalation Notice Interval'
    escalation_notice_start = 'Escalation Notice Start'
    expiration_notice_interval = 'Expiration Notice Interval'
    expiration_notice_start = 'Expiration Notice Start'
    expiration = 'Expiration'
    guid = 'GUID'
    last_notification = 'Last Notification'
    managed_by = 'Managed By'
    metadata = 'Metadata'
    protection_key = 'Protection Key'
    reference = 'Reference'
    shared = 'Shared'
    vault_id = 'Vault Id'
    workflow = 'Workflow'
    workflow_block = 'Workflow Block'


class CredentialAttributes:
    class Amazon(_CredentialAttributes):
        authentication_credential = 'Authentication Credential'
        region_code = 'Region Code'
        role = 'Role'
        username = 'Username'
        web_service_url = 'Web Service URL'

    class Certificate(_CredentialAttributes):
        certificate = 'Certificate'
        username = 'Username'

    class Generic(_CredentialAttributes):
        pass

    class Password(_CredentialAttributes):
        pass

    class PrivateKey(_CredentialAttributes):
        username = 'Username'

    class UsernamePassword(_CredentialAttributes):
        username = 'Username'


class _CertificateAuthorityAttributes:
    additional_field = 'Additional Field'
    algorithm = 'Algorithm'
    concurrent_connection_limit = 'Concurrent Connection Limit'
    contact = 'Contact'
    created_by = 'Created By'
    credential = 'Credential'
    credits = 'Credits'
    credits_alert = 'Credits Alert'
    credits_used = 'Credits Used'
    description = 'Description'
    disabled = 'Disabled'
    driver_arguments = 'Driver Arguments'
    driver_name = 'Driver Name'
    enhanced_key_usage = 'Enhanced Key Usage'
    escalation_contact = 'Escalation Contact'
    guid = 'GUID'
    host = 'Host'
    key_usage = 'Key Usage'
    managed_by = 'Managed By'
    manual_approval = 'Manual Approval'
    metadata = 'Metadata'
    port = 'Port'
    protection_key = 'Protection Key'
    rank = 'Rank'
    reference = 'Reference'
    renewal_window = 'Renewal Window'
    retry_count = 'Retry Count'
    retry_interval = 'Retry Interval'
    san_enabled= 'SAN Enabled'
    signature_algorithm = 'Signature Algorithm'
    specific_end_date_enabled = 'Specific End Date Enabled'
    template = 'Template'
    test_account = 'Test Account'
    timeout = 'Timeout'
    validatity_period = 'Validity Period'
    vault_id = 'Vault Id'
    workflow = 'Workflow'
    workflow_block = 'Workflow Block'


class CertificateAuthorityAttributes:
    class SelfSigned(_CertificateAuthorityAttributes):
        pass

    class MSCA(_CertificateAuthorityAttributes):
        given_name = 'Given Name'
        enrollment_agent_certificate = 'Enrollment Agent Certificate'
        host = 'Host'
        include_cn_as_san = 'Include CN as SAN'
        template = 'Template'


class _DeviceAttributes:
    concurrent_connection_limit = 'Concurrent Connection Limit'
    connection_method = 'Connection Method'
    contact = 'Contact'
    created_by = 'Created By'
    credential = 'Credential'
    description = 'Description'
    disabled = 'Disabled'
    enforce_known_host = 'Enforce Known Host'
    escalation_contact = 'Escalation Contact'
    guid = 'GUID'
    global_sudo = 'Global sudo'
    host = 'Host'
    last_known_fingerprint = 'Last Known Fingerprint'
    last_known_key_type = 'Last Known Key Type'
    location = 'Location'
    managed_by = 'Managed By'
    metadata = 'Metadata'
    port = 'Port'
    reference = 'Reference'
    secondary_credential = 'Secondary Credential'
    sudo_password_delay = 'Sudo Password Delay'
    temp_directory = 'Temp Directory'
    terminal_columns = 'Terminal Columns'
    terminal_rows = 'Terminal Rows'
    terminal_type = 'Terminal Type'
    timeout = 'Timeout'
    trusted_fingerprint = 'Trusted Fingerprint'
    trusted_key_type = 'Trusted Key Type'
    workflow = 'Workflow'
    workflow_block = 'Workflow Block'


class DeviceAttributes:
    class Device(_DeviceAttributes):
        agentless_discovery_stage = 'Agentless Discovery Stage'
        agentless_discovery_status = 'Agentless Discovery Status'
        algorithm = 'Algorithm'
        allow_agentless_discovery_and_remediation = 'Allow Agentless Discovery and Remediation'
        allow_duplicate_private_keys = 'Allow Duplicate Private Keys'
        allow_from = 'Allow From'
        allow_multiple_authorized_keys = 'Allow Multiple Authorized Keys'
        allow_root_access = 'Allow Root Access'
        allow_shared_server_accounts = 'Allow Shared Server Accounts'
        allow_ssh1 = 'Allow Ssh1'
        allow_unencrypted_private_keys = 'Allow Unencrypted Private Keys'
        allowed_algorithm = 'Allowed Algorithm'
        allowed_command = 'Allowed Command'
        allowed_vendor_types = 'Allowed Vendor Types'
        approver = 'Approver'
        automatic_rotation_cleanup_wait = 'Automatic Rotation Cleanup Wait'
        automatic_rotation_enabled = 'Automatic Rotation Enabled'
        automatic_rotation_interval = 'Automatic Rotation Interval'
        automatic_rotation_lead_time = 'Automatic Rotation Lead Time'
        bulk_provisioning_stage = 'Bulk Provisioning Stage'
        bulk_provisioning_status = 'Bulk Provisioning Status'
        client_id = 'Client ID'
        client_machine_id = 'Client Machine ID'
        cloud_instance_id = 'Cloud Instance ID'
        cloud_region = 'Cloud Region'
        cloud_service = 'Cloud Service'
        deny_form = 'Deny Form'
        deny_multiple_authentication_failures = 'Deny Multiple Authentication Failures'
        disabled_on = 'Disabled On'
        discovered_by_dn = 'Discovered By DN'
        environment = 'Environment'
        file_validation_error = 'File Validation Error'
        file_validation_result = 'File Validation Result'
        host_trusts = 'Host Trusts'
        jump_server_dn = 'Jump Server DN'
        key_bit_strength = 'Key Bit Strength'
        known_hosts = 'Known Hosts'
        last_attempt_to_get_client_subsystem_record = 'Last Attempt To Get Client Subsystem Record'
        last_discovery_date = 'Last Discovery Date'
        last_discovery_planned = 'Last Discovery Planned'
        last_validation = 'Last Validation'
        last_validation_result = 'Last Validation Result'
        management_type = 'Management Type'
        manual_approval = 'Manual Approval'
        maximum_key_age = 'Maximum Key Age'
        minimum_key_bit_strength = 'Minimum Key Bit Strength'
        onboard_discovery_dn = 'Onboard Discovery Dn'
        onboard_discovery_stage = 'Onboard Discovery Stage'
        onboard_discovery_status = 'Onboard Discovery Status'
        onboard_discovery_to_do = 'Onboard Discovery To Do'
        placement_job_dn = 'Placement Job Dn'
        previous_connection_credential_hash = 'Previous Connection Credential Hash'
        privilege_elevation_command = 'Privilege Elevation Command'
        protection_key = 'Protection Key'
        remote_server_type = 'Remote Server Type'
        required_options = 'Required Options'
        required_sync_confirmation = 'Required Sync Confirmation'
        root_server_access = 'Root Server Access'
        ssh_key_encryption = 'SSH Key Encryption'
        ssl_listen_host = 'SSL Listen Host'
        ssl_listen_port = 'SSL Listen Port'
        server_access = 'Server Access'
        ssh_device_status = 'Ssh Device Status'
        ssh_device_type = 'Ssh Device Type'
        status = 'Status'
        system_owned_keys = 'System Owned Keys'
        trusted_root_users = 'Trusted Root Users'
        trusted_users = 'Trusted Users'
        update_cache = 'Update Cache'
        use_specified_host = 'Use Specified Host'
        validation_disabled = 'Validation Disabled'
        validation_errors = 'Validation Errors'
        validation_results = 'Validation Results'

    class JumpServer(_DeviceAttributes):
        consumers = 'Consumers'
        ssh_connection_string = 'SSH Connection String'
        ssh_version = 'SSH Version'
