class ResultCodes:
    Config = {
          1 : 'Success',
          2 : 'InvalidArgument',
          3 : 'InvalidArgumentRange',
          4 : 'MismatchedArguments',
          5 : 'NotImplemented',
          6 : 'InvalidDestinationList',
          7 : 'InsufficientPrivileges',
          8 : 'InvalidOperation',
          9 : 'UnexpectedAssemblyError',
         10 : 'OutOfMemory',
        100 : 'AttributeDoesNotExist',
        101 : 'AttributeAlreadyExists',
        102 : 'AttributeNotFound',
        103 : 'AttributeValueExists',
        104 : 'AttributeStillInUse',
        105 : 'AttributeNameTooLong',
        106 : 'AttributeReferenceDoesNotExist',
        107 : 'AttributeSyntaxCollision',
        108 : 'AttributePropertyCollision',
        109 : 'CannotRemoveMandatory',
        110 : 'AttributeValueIsMandatory',
        111 : 'AttributeValueTooLong',
        112 : 'IllegalAttributeForClass',
        113 : 'InvalidAttributeDN',
        114 : 'AttributeValueDoesNotExist',
        115 : 'AttributeIsSingleValued',
        116 : 'AttributeIsReadOnly',
        117 : 'AttributeIsHidden',
        200 : 'ClassDoesNotExist',
        201 : 'ClassAlreadyExists',
        202 : 'ClassStillInUse',
        203 : 'ClassNameTooLong',
        204 : 'ClassInvalidSuperClass',
        205 : 'ClassInvalidContainmentClass',
        206 : 'ClassInvalidNamingAttribute',
        207 : 'ClassInvalidMandatoryAttribute',
        208 : 'ClassInvalidOptionalAttribute',
        209 : 'ClassInvalidName',
        210 : 'ClassInvalidContainmentSubClass',
        211 : 'ClassInvalidPolicyClass',
        300 : 'PolicyDoesNotExist',
        301 : 'PolicyLockStateCollision',
        350 : 'LockNameAlreadyExists',
        351 : 'LockNameDoesNotExist',
        352 : 'LockNameOwnedByAnother',
        353 : 'LockNameLimitReached',
        354 : 'LockNameAttemptTimedOut',
        400 : 'ObjectDoesNotExist',
        401 : 'ObjectAlreadyExists',
        402 : 'ObjectHasChildren',
        403 : 'ObjectNameTooLong',
        404 : 'ObjectDepthTooDeep',
        405 : 'ObjectInvalidName',
        406 : 'ObjectInvalidClass',
        407 : 'ObjectInvalidContainment',
        408 : 'ObjectMandatoryMissing',
        409 : 'ObjectIsReadOnly',
        410 : 'ObjectInvalidOperation',
        500 : 'DriverMissingDSN',
        501 : 'DriverMissingDatabaseName',
        502 : 'DriverDatabaseError',
        503 : 'DriverTransactionError',
        504 : 'DriverTransactionCollision',
        505 : 'DriverGenerationUpdateError',
        600 : 'CacheLockException',
        601 : 'CacheEntryNotFound',
        602 : 'CacheEntryAlreadyExists',
        603 : 'CacheEntryIsSuperior',
        604 : 'CacheEntryIsIncompatible',
        700 : 'XmlInvalidStructure',
        701 : 'XmlMissingNaming',
        702 : 'XmlMissingSyntax',
        703 : 'XmlMissingProperty',
        704 : 'XmlUnknownElementAttribute'
    }
    
    Credential = {
           1: 'Success',
           2: 'InvalidArgument',
           3: 'InvalidArgumentRange',
           4: 'MismatchedArguments',
           5: 'NotImplemented',
           6: 'InvalidDestinationList',
           7: 'InsufficientPrivileges',
           8: 'InvalidOperation',
           9: 'UnexpectedAssemblyError',
          10: 'OutOfMemory',
         100: 'AttributeDoesNotExist',
         101: 'AttributeAlreadyExists',
         102: 'AttributeNotFound',
         103: 'AttributeValueExists',
         104: 'AttributeStillInUse',
         105: 'AttributeNameTooLong',
         106: 'AttributeReferenceDoesNotExist',
         107: 'AttributeSyntaxCollision',
         108: 'AttributePropertyCollision',
         109: 'CannotRemoveMandatory',
         110: 'AttributeValueIsMandatory',
         111: 'AttributeValueTooLong',
         112: 'IllegalAttributeForClass',
         113: 'InvalidAttributeDN',
         114: 'AttributeValueDoesNotExist',
         115: 'AttributeIsSingleValued',
         116: 'AttributeIsReadOnly',
         117: 'AttributeIsHidden',
         200: 'ClassDoesNotExist',
         201: 'ClassAlreadyExists',
         202: 'ClassStillInUse',
         203: 'ClassNameTooLong',
         204: 'ClassInvalidSuperClass',
         205: 'ClassInvalidContainmentClass',
         206: 'ClassInvalidNamingAttribute',
         207: 'ClassInvalidMandatoryAttribute',
         208: 'ClassInvalidOptionalAttribute',
         209: 'ClassInvalidName',
         210: 'ClassInvalidContainmentSubClass',
         300: 'PolicyDoesNotExist',
         301: 'PolicyLockStateCollision',
         350: 'LockNameAlreadyExists',
         351: 'LockNameDoesNotExist',
         352: 'LockNameOwnedByAnother',
         353: 'LockNameLimitReached',
         354: 'LockNameAttemptTimedOut',
         400: 'Disadvantageous',
         401: 'ObjectAlreadyExists',
         402: 'ObjectHasChildren',
         403: 'ObjectNameTooLong',
         404: 'ObjectDepthTooDeep',
         405: 'ObjectInvalidName',
         406: 'ObjectInvalidClass',
         407: 'ObjectInvalidContainment',
         408: 'ObjectMandatoryMissing',
         409: 'ObjectIsReadOnly',
         410: 'ObjectInvalidOperation',
         500: 'DriverMissingDSN',
         501: 'DriverMissingDatabaseName',
         502: 'DriverDatabaseError',
         503: 'DriverTransactionError',
         504: 'DriverTransactionCollision',
         505: 'DriverGenerationUpdateError',
         600: 'CacheLockException',
         601: 'CacheEntryNotFound',
         602: 'CacheEntryAlreadyExists',
         603: 'CacheEntryIsSuperior',
         604: 'CacheEntryIsIncompatible',
         700: 'XmlInvalidStructure',
         701: 'XmlMissingNaming',
         702: 'XmlMissingSyntax',
         703: 'XmlMissingProperty',
         704: 'XmlUnknownElementAttribute',
        1000: 'SecretStoreFailed',
        1001: 'AddAttributeFailed',
        1002: 'UnexpectedException',
        1003: 'PartialDeleteFailure',
        1004: 'CredentialTypeMismatch',
        1005: 'NoDriver',
        1006: 'VaultTypeMismatch',
        1007: 'DriverDenied',
        1008: 'VaultDataUnrecognized'
    }

    CertificatesWorkToDo = {
          0: 'Success',
          1: 'MissingDSN',
          2: 'MissingDatabaseName',
         99: 'UnexpectedAssemblyError',
        100: 'DatabaseError',
        101: 'DatabaseConnectionUnavailable',
        102: 'TransactionError',
        103: 'TransactionCollision',
        200: 'InsufficientPrivileges',
        300: 'IdentifierDoesNotExist',
        301: 'IdentifierAlreadyExists'
    }
