from pytpp.tools.helpers.date_converter import from_date_string
from pytpp.plugins.properties.response_objects.dataclasses import certificate_inventory


def CertificateDetails(response_object: dict):
    if not isinstance(response_object, dict):
        response_object = {}
    return certificate_inventory.CertificateDetails(
        allowed_app_type=response_object.get('allowedAppType'),
        aperture_status=response_object.get('apertureStatus'),
        approver=response_object.get('approver'),
        city=response_object.get('city'),
        common_name=response_object.get('commonName'),
        contact=response_object.get('contact'),
        country=response_object.get('country'),
        days_to_expire=response_object.get('daysToExpire'),
        description=response_object.get('description'),
        dn=response_object.get('dn'),
        dns_sans=response_object.get('dnsSans'),
        domain=response_object.get('domain'),
        elliptic_curve=response_object.get('ellipticCurve'),
        email_sans=response_object.get('emailSans'),
        error_details=response_object.get('errorDetails'),
        id=response_object.get('id'),
        installations=response_object.get('installations'),
        ip_sans=response_object.get('ipSans'),
        is_disabled=response_object.get('isDisabled'),
        is_in_error=response_object.get('isInError'),
        is_rename_allowed=response_object.get('isRenameAllowed'),
        is_validation_enabled=response_object.get('isValidationEnabled'),
        issuer=response_object.get('issuer'),
        key_algorithm=response_object.get('keyAlgorithm'),
        key_size=response_object.get('keySize'),
        last_renewed_by=response_object.get('lastRenewedBy'),
        management_type=response_object.get('managementType'),
        name=response_object.get('name'),
        organization=response_object.get('organization'),
        organizational_unit=response_object.get('organizationalUnit'),
        parent_dn=response_object.get('parentDn'),
        renewal_date=from_date_string(response_object.get('renewalDate')),
        revocation_status=response_object.get('revocationStatus'),
        risks=response_object.get('risks'),
        serial_number=response_object.get('serialNumber'),
        signature_algorithm=response_object.get('signatureAlgorithm'),
        single_click_actions=response_object.get('singleClickActions'),
        state=response_object.get('state'),
        status_details=response_object.get('statusDetails'),
        tls_endpoints=response_object.get('tlsEndpoints'),
        trust_net_reputation_score=response_object.get('trustNetReputationScore'),
        trust_net_reviewed_by=response_object.get('trustNetReviewedBy'),
        trust_net_reviewed_date=from_date_string(response_object.get('trustNetReviewedDate')),
        upn_sans=response_object.get('upnSans'),
        uri_sans=response_object.get('uriSans'),
        usage=response_object.get('usage'),
        use_manual_csr=response_object.get('useManualCsr'),
        valid_from=from_date_string(response_object.get('validFrom')),
        valid_to=from_date_string(response_object.get('validTo')),
        validation_state=response_object.get('validationState'),
        validity_period_days=response_object.get('validityPeriodDays'),
    )
