class Field:
    access ='access'
    accessAndName = 'accessAndName'
    algorithm = 'algorithm'
    fingerprint_md5 = 'fingerprintMD5'
    fingerprint_sha256 = 'fingerprintSHA256'
    guid = 'guid'
    host_key_devices = 'hostKeyDevices'
    is_unmatched = 'isUnmatched'
    key_length = 'keyLength'
    keyset_type = 'keysetType'
    key_type = 'keyType'
    last_rotation_date = 'lastRotationDate'
    last_used_date = 'lastUsedDate'
    last_used_date_min = 'lastUsedDateMin'
    needs_to_be_provisioned = 'needsToBeProvisioned'
    nist_codes = 'nistCodes'
    private_keys_count = 'privateKeysCount'
    public_keys_count = 'publicKeysCount'
    risks = 'risks'
    rotation_scheduled = 'rotationScheduled'
    rotation_error = 'rotationError'
    status = 'status'
    trusted_devices = 'trustedDevices'
    trust_id = 'trustId'
    unknown_passphrase = 'unknownPassphrase'
    unmatched_trust_id = 'unmatchedTrustId'


class Filter:
    account = 'SshAccount'
    algorithm = 'SshAlgorithm'
    critical_alerts = 'SshCriticalAlerts'
    device = 'SshDevice'
    folder = 'SshLocations'
    key_size = 'SshKeyLength'
    key_usage = 'SshKeyUsage'
    keyset_type = 'SshKeysetType'
    nist_control_number = 'SshNistCodes'
    risks = 'SshRisks'
    rotation_date = 'SshRotationDate'
    status = 'SshStatus'
    trusts = 'SshTrusts'
    authorized_key_comment = 'SshAuthorizedKeyComment'
