from __future__ import annotations
from datetime import datetime
from pytpp.api.api_base import OutputModel, ApiField


class Certificate(OutputModel):
    authentication: str = ApiField(alias='Authentication')
    check_value: str = ApiField(alias='CheckValue')
    created_on: datetime = ApiField(alias='CreatedOn')
    encipherment: bool = ApiField(alias='Encipherment')
    end_date: datetime = ApiField(alias='EndDate')
    environment_type: int = ApiField(alias='EnvironmentType')
    handle: int = ApiField(alias='Handle')
    id: int = ApiField(alias='Id')
    issuer: str = ApiField(alias='Issuer')
    key_context: str = ApiField(alias='KeyContext')
    key_id: str = ApiField(alias='KeyId')
    label: str = ApiField(alias='Label')
    object_type: int = ApiField(alias='ObjectType')
    signing: bool = ApiField(alias='Signing')
    start_date: datetime = ApiField(alias='StartDate')
    subject: str = ApiField(alias='Subject')
    token: bool = ApiField(alias='Token')
    trusted: bool = ApiField(alias='Trusted')
    value: str = ApiField(alias='Value')


class PrivateKey(OutputModel):
    authentication: bool = ApiField(alias='Authentication')
    created_on: datetime = ApiField(alias='CreatedOn')
    curve: str = ApiField(alias='Curve')
    decrypt: bool = ApiField(alias='Decrypt')
    encipherment: bool = ApiField(alias='Encipherment')
    environment_type: int = ApiField(alias='EnvironmentType')
    exponent: str = ApiField(alias='Exponent')
    handle: int = ApiField(alias='Handle')
    id: str = ApiField(alias='Id')
    key_context: str = ApiField(alias='KeyContext')
    key_id: str = ApiField(alias='KeyId')
    key_type: str = ApiField(alias='KeyType')
    label: str = ApiField(alias='Label')
    modulus: str = ApiField(alias='Modulus')
    object_type: int = ApiField(alias='ObjectType')
    params: str = ApiField(alias='Params')
    private: bool = ApiField(alias='Private')
    sign: bool = ApiField(alias='Sign')
    signing: bool = ApiField(alias='Signing')
    token: bool = ApiField(alias='Token')
    unwrap: bool = ApiField(alias='Unwrap')


class PublicKey(OutputModel):
    authentication: bool = ApiField(alias='Authentication')
    bits: str = ApiField(alias='Bits')
    created_on: datetime = ApiField(alias='CreatedOn')
    curve: str = ApiField(alias='Curve')
    ec_point: str = ApiField(alias='ECPoint')
    encipherment: bool = ApiField(alias='Encipherment')
    encrypt: str = ApiField(alias='Encrypt')
    environment_type: int = ApiField(alias='EnvironmentType')
    exponent: str = ApiField(alias='Exponent')
    handle: int = ApiField(alias='Handle')
    id: str = ApiField(alias='Id')
    key_context: str = ApiField(alias='KeyContext')
    key_id: str = ApiField(alias='KeyId')
    key_type: str = ApiField(alias='KeyType')
    label: str = ApiField(alias='Label')
    modulus: str = ApiField(alias='Modulus')
    object_type: int = ApiField(alias='ObjectType')
    params: str = ApiField(alias='Params')
    signing: bool = ApiField(alias='Signing')
    token: bool = ApiField(alias='Token')
    verify: str = ApiField(alias='Verify')
    wrap: str = ApiField(alias='Wrap')
