class ResultCodes:
    Config = {
          1 : {'Config Result': 'Success'},
          2 : {'Config Result': 'InvalidArgument'},
          3 : {'Config Result': 'InvalidArgumentRange'},
          4 : {'Config Result': 'MismatchedArguments'},
          5 : {'Config Result': 'NotImplemented'},
          6 : {'Config Result': 'InvalidDestinationList'},
          7 : {'Config Result': 'InsufficientPrivileges'},
          8 : {'Config Result': 'InvalidOperation'},
          9 : {'Config Result': 'UnexpectedAssemblyError'},
         10 : {'Config Result': 'OutOfMemory'},
        100 : {'Config Result': 'AttributeDoesNotExist'},
        101 : {'Config Result': 'AttributeAlreadyExists'},
        102 : {'Config Result': 'AttributeNotFound'},
        103 : {'Config Result': 'AttributeValueExists'},
        104 : {'Config Result': 'AttributeStillInUse'},
        105 : {'Config Result': 'AttributeNameTooLong'},
        106 : {'Config Result': 'AttributeReferenceDoesNotExist'},
        107 : {'Config Result': 'AttributeSyntaxCollision'},
        108 : {'Config Result': 'AttributePropertyCollision'},
        109 : {'Config Result': 'CannotRemoveMandatory'},
        110 : {'Config Result': 'AttributeValueIsMandatory'},
        111 : {'Config Result': 'AttributeValueTooLong'},
        112 : {'Config Result': 'IllegalAttributeForClass'},
        113 : {'Config Result': 'InvalidAttributeDN'},
        114 : {'Config Result': 'AttributeValueDoesNotExist'},
        115 : {'Config Result': 'AttributeIsSingleValued'},
        116 : {'Config Result': 'AttributeIsReadOnly'},
        117 : {'Config Result': 'AttributeIsHidden'},
        200 : {'Config Result': 'ClassDoesNotExist'},
        201 : {'Config Result': 'ClassAlreadyExists'},
        202 : {'Config Result': 'ClassStillInUse'},
        203 : {'Config Result': 'ClassNameTooLong'},
        204 : {'Config Result': 'ClassInvalidSuperClass'},
        205 : {'Config Result': 'ClassInvalidContainmentClass'},
        206 : {'Config Result': 'ClassInvalidNamingAttribute'},
        207 : {'Config Result': 'ClassInvalidMandatoryAttribute'},
        208 : {'Config Result': 'ClassInvalidOptionalAttribute'},
        209 : {'Config Result': 'ClassInvalidName'},
        210 : {'Config Result': 'ClassInvalidContainmentSubClass'},
        211 : {'Config Result': 'ClassInvalidPolicyClass'},
        300 : {'Config Result': 'PolicyDoesNotExist'},
        301 : {'Config Result': 'PolicyLockStateCollision'},
        350 : {'Config Result': 'LockNameAlreadyExists'},
        351 : {'Config Result': 'LockNameDoesNotExist'},
        352 : {'Config Result': 'LockNameOwnedByAnother'},
        353 : {'Config Result': 'LockNameLimitReached'},
        354 : {'Config Result': 'LockNameAttemptTimedOut'},
        400 : {'Config Result': 'ObjectDoesNotExist'},
        401 : {'Config Result': 'ObjectAlreadyExists'},
        402 : {'Config Result': 'ObjectHasChildren'},
        403 : {'Config Result': 'ObjectNameTooLong'},
        404 : {'Config Result': 'ObjectDepthTooDeep'},
        405 : {'Config Result': 'ObjectInvalidName'},
        406 : {'Config Result': 'ObjectInvalidClass'},
        407 : {'Config Result': 'ObjectInvalidContainment'},
        408 : {'Config Result': 'ObjectMandatoryMissing'},
        409 : {'Config Result': 'ObjectIsReadOnly'},
        410 : {'Config Result': 'ObjectInvalidOperation'},
        500 : {'Config Result': 'DriverMissingDSN'},
        501 : {'Config Result': 'DriverMissingDatabaseName'},
        502 : {'Config Result': 'DriverDatabaseError'},
        503 : {'Config Result': 'DriverTransactionError'},
        504 : {'Config Result': 'DriverTransactionCollision'},
        505 : {'Config Result': 'DriverGenerationUpdateError'},
        600 : {'Config Result': 'CacheLockException'},
        601 : {'Config Result': 'CacheEntryNotFound'},
        602 : {'Config Result': 'CacheEntryAlreadyExists'},
        603 : {'Config Result': 'CacheEntryIsSuperior'},
        604 : {'Config Result': 'CacheEntryIsIncompatible'},
        700 : {'Config Result': 'XmlInvalidStructure'},
        701 : {'Config Result': 'XmlMissingNaming'},
        702 : {'Config Result': 'XmlMissingSyntax'},
        703 : {'Config Result': 'XmlMissingProperty'},
        704 : {'Config Result': 'XmlUnknownElementAttribute'},
    }
    
    Credential = {
           1: {'Credential Result': 'Success'},
           2: {'Credential Result': 'InvalidArgument'},
           3: {'Credential Result': 'InvalidArgumentRange'},
           4: {'Credential Result': 'MismatchedArguments'},
           5: {'Credential Result': 'NotImplemented'},
           6: {'Credential Result': 'InvalidDestinationList'},
           7: {'Credential Result': 'InsufficientPrivileges'},
           8: {'Credential Result': 'InvalidOperation'},
           9: {'Credential Result': 'UnexpectedAssemblyError'},
          10: {'Credential Result': 'OutOfMemory'},
         100: {'Credential Result': 'AttributeDoesNotExist'},
         101: {'Credential Result': 'AttributeAlreadyExists'},
         102: {'Credential Result': 'AttributeNotFound'},
         103: {'Credential Result': 'AttributeValueExists'},
         104: {'Credential Result': 'AttributeStillInUse'},
         105: {'Credential Result': 'AttributeNameTooLong'},
         106: {'Credential Result': 'AttributeReferenceDoesNotExist'},
         107: {'Credential Result': 'AttributeSyntaxCollision'},
         108: {'Credential Result': 'AttributePropertyCollision'},
         109: {'Credential Result': 'CannotRemoveMandatory'},
         110: {'Credential Result': 'AttributeValueIsMandatory'},
         111: {'Credential Result': 'AttributeValueTooLong'},
         112: {'Credential Result': 'IllegalAttributeForClass'},
         113: {'Credential Result': 'InvalidAttributeDN'},
         114: {'Credential Result': 'AttributeValueDoesNotExist'},
         115: {'Credential Result': 'AttributeIsSingleValued'},
         116: {'Credential Result': 'AttributeIsReadOnly'},
         117: {'Credential Result': 'AttributeIsHidden'},
         200: {'Credential Result': 'ClassDoesNotExist'},
         201: {'Credential Result': 'ClassAlreadyExists'},
         202: {'Credential Result': 'ClassStillInUse'},
         203: {'Credential Result': 'ClassNameTooLong'},
         204: {'Credential Result': 'ClassInvalidSuperClass'},
         205: {'Credential Result': 'ClassInvalidContainmentClass'},
         206: {'Credential Result': 'ClassInvalidNamingAttribute'},
         207: {'Credential Result': 'ClassInvalidMandatoryAttribute'},
         208: {'Credential Result': 'ClassInvalidOptionalAttribute'},
         209: {'Credential Result': 'ClassInvalidName'},
         210: {'Credential Result': 'ClassInvalidContainmentSubClass'},
         300: {'Credential Result': 'PolicyDoesNotExist'},
         301: {'Credential Result': 'PolicyLockStateCollision'},
         350: {'Credential Result': 'LockNameAlreadyExists'},
         351: {'Credential Result': 'LockNameDoesNotExist'},
         352: {'Credential Result': 'LockNameOwnedByAnother'},
         353: {'Credential Result': 'LockNameLimitReached'},
         354: {'Credential Result': 'LockNameAttemptTimedOut'},
         400: {'Credential Result': 'Disadvantageous'},
         401: {'Credential Result': 'ObjectAlreadyExists'},
         402: {'Credential Result': 'ObjectHasChildren'},
         403: {'Credential Result': 'ObjectNameTooLong'},
         404: {'Credential Result': 'ObjectDepthTooDeep'},
         405: {'Credential Result': 'ObjectInvalidName'},
         406: {'Credential Result': 'ObjectInvalidClass'},
         407: {'Credential Result': 'ObjectInvalidContainment'},
         408: {'Credential Result': 'ObjectMandatoryMissing'},
         409: {'Credential Result': 'ObjectIsReadOnly'},
         410: {'Credential Result': 'ObjectInvalidOperation'},
         500: {'Credential Result': 'DriverMissingDSN'},
         501: {'Credential Result': 'DriverMissingDatabaseName'},
         502: {'Credential Result': 'DriverDatabaseError'},
         503: {'Credential Result': 'DriverTransactionError'},
         504: {'Credential Result': 'DriverTransactionCollision'},
         505: {'Credential Result': 'DriverGenerationUpdateError'},
         600: {'Credential Result': 'CacheLockException'},
         601: {'Credential Result': 'CacheEntryNotFound'},
         602: {'Credential Result': 'CacheEntryAlreadyExists'},
         603: {'Credential Result': 'CacheEntryIsSuperior'},
         604: {'Credential Result': 'CacheEntryIsIncompatible'},
         700: {'Credential Result': 'XmlInvalidStructure'},
         701: {'Credential Result': 'XmlMissingNaming'},
         702: {'Credential Result': 'XmlMissingSyntax'},
         703: {'Credential Result': 'XmlMissingProperty'},
         704: {'Credential Result': 'XmlUnknownElementAttribute'},
        1000: {'Credential Result': 'SecretStoreFailed'},
        1001: {'Credential Result': 'AddAttributeFailed'},
        1002: {'Credential Result': 'UnexpectedException'},
        1003: {'Credential Result': 'PartialDeleteFailure'},
        1004: {'Credential Result': 'CredentialTypeMismatch'},
        1005: {'Credential Result': 'NoDriver'},
        1006: {'Credential Result': 'VaultTypeMismatch'},
        1007: {'Credential Result': 'DriverDenied'},
        1008: {'Credential Result': 'VaultDataUnrecognized'}
    }
