from __future__ import annotations
from pytpp.api.api_base import OutputModel, ApiField
from typing import List, Dict
from datetime import datetime


class CertificateDetails(OutputModel):
    allowed_app_type: str = ApiField(alias='allowedAppType')
    aperture_status: List[str] = ApiField(alias='apertureStatus', default_factory=list)
    approver: List[str] = ApiField(alias='approver', default_factory=list)
    city: str = ApiField(alias='city')
    common_name: str = ApiField(alias='commonName')
    contact: List[str] = ApiField(alias='contact', default_factory=list)
    country: str = ApiField(alias='country')
    days_to_expire: int = ApiField(alias='daysToExpire')
    description: str = ApiField(alias='description')
    dn: str = ApiField(alias='dn')
    dns_sans: List[str] = ApiField(alias='dnsSans', default_factory=list)
    domain: str = ApiField(alias='domain')
    elliptic_curve: str = ApiField(alias='ellipticCurve')
    email_sans: List[str] = ApiField(alias='emailSans', default_factory=list)
    error_details: str = ApiField(alias='errorDetails')
    id: str = ApiField(alias='id')
    installations: int = ApiField(alias='installations')
    ip_sans: List[str] = ApiField(alias='ipSans', default_factory=list)
    is_disabled: bool = ApiField(alias='isDisabled')
    is_in_error: bool = ApiField(alias='isInError')
    is_rename_allowed: bool = ApiField(alias='isRenameAllowed')
    is_validation_enabled: bool = ApiField(alias='isValidationEnabled')
    issuer: str = ApiField(alias='issuer')
    key_algorithm: str = ApiField(alias='keyAlgorithm')
    key_size: int = ApiField(alias='keySize')
    last_renewed_by: List[str] = ApiField(alias='lastRenewedBy', default_factory=list)
    management_type: str = ApiField(alias='managementType')
    name: str = ApiField(alias='name')
    organization: str = ApiField(alias='organization')
    organizational_unit: List[str] = ApiField(alias='organizationalUnit', default_factory=list)
    parent_dn: str = ApiField(alias='parentDn')
    renewal_date: datetime = ApiField(alias='renewalDate')
    revocation_status: str = ApiField(alias='revocationStatus')
    risks: List[str] = ApiField(alias='risks', default_factory=list)
    serial_number: str = ApiField(alias='serialNumber')
    signature_algorithm: str = ApiField(alias='signatureAlgorithm')
    single_click_actions: List[str] = ApiField(alias='singleClickActions', default_factory=list)
    state: str = ApiField(alias='state')
    status_details: Dict[str, List[str]] = ApiField(alias='statusDetails')
    tls_endpoints: int = ApiField(alias='tlsEndpoints')
    trust_net_reputation_score: int = ApiField(alias='trustNetReputationScore')
    trust_net_reviewed_by: str = ApiField(alias='trustNetReviewedBy')
    trust_net_reviewed_date: datetime = ApiField(alias='trustNetReviewedDate')
    upn_sans: List[str] = ApiField(alias='upnSans', default_factory=list)
    uri_sans: List[str] = ApiField(alias='uriSans', default_factory=list)
    usage: str = ApiField(alias='usage')
    use_manual_csr: bool = ApiField(alias='useManualCsr')
    valid_from: datetime = ApiField(alias='validFrom')
    valid_to: datetime = ApiField(alias='validTo')
    validation_state: str = ApiField(alias='validationState')
    validity_period_days: int = ApiField(alias='validityPeriodDays')
